---
volumes:
  redis_data_dev:
  rabbitmq_data_dev:

networks:
  auto-xkcd_devnet:

services:
  celery_beat:
    container_name: ${CELERY_BEAT_CONTAINER_NAME:-auto-xkcd_celery_beat}
    restart: unless-stopped
    build:
      context: ..
      # dockerfile: ./containers/dockerfiles/celery.Dockerfile
      dockerfile: ./containers/dockerfiles/dev.Dockerfile
      target: celery_beat
    working_dir: /project
    # user: appuser
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - ./envs/dev/app.env
    command: ["uv", "run", "scripts/celery/start_celery.py", "-m", "beat"]
    # ## Uncomment for debugging
    # # command: ["/bin/bash"]
    volumes:
      - ../applications:/project/applications
      - ../packages:/project/packages
      - ../scripts:/project/scripts
      # - ../src:/project/src
      - ./container_data/auto-xkcd/db:/auto-xkcd/db
    networks:
      - auto-xkcd_devnet

  celery_worker:
    container_name: ${CELERY_WORKER_CONTAINER_NAME:-auto-xkcd_celery_worker}
    restart: unless-stopped
    build:
      context: ..
      # dockerfile: ./containers/dockerfiles/celery.Dockerfile
      dockerfile: ./containers/dockerfiles/dev.Dockerfile
      target: celery_worker
    working_dir: /project
    # user: appuser
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - ./envs/dev/app.env
    command: ["uv", "run", "scripts/celery/start_celery.py", "-m", "worker"]
    # command: ["uv", "run", "scripts/debug/debug_settings.py"]
    volumes:
      - ../applications:/project/applications
      - ../packages:/project/packages
      - ../scripts:/project/scripts
      # - ../src:/project/src
      - ./container_data/auto-xkcd/celery_worker/logs:/project/logs
    networks:
      - auto-xkcd_devnet

  redis:
    image: redis:alpine
    container_name: auto-xkcd_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-redis}"]
    env_file:
      - ./envs/dev/messaging.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
    volumes:
      - ${REDIS_DATA_DIR:-redis_data_dev}:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - auto-xkcd_devnet

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: auto-xkcd_redis-commander
    restart: unless-stopped
    env_file:
      - ./envs/dev/messaging.env
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
      HTTP_USER: ${REDIS_COMMANDER_HTTP_USER:-admin}
      HTTP_PASSWORD: ${REDIS_COMMANDER_HTTP_PASSWORD:-admin}
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081
    depends_on:
      - redis
    networks:
      - auto-xkcd_devnet

  rabbitmq:
    image: rabbitmq:management
    container_name: auto-xkcd_rabbitmq
    restart: unless-stopped
    env_file:
      - ./envs/dev/messaging.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-rabbitmq}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-rabbitmq}
    volumes:
      - ${RABBITMQ_DATA_DIR:-rabbitmq_data_dev}:/var/lib/rabbitmq
    ports:
      - ${RABBITMQ_AMPQ_PORT:-5672}:5672
      - ${RABBITMQ_HTTP_PORT:-15672}:15672
    networks:
      - auto-xkcd_devnet
