## [DEVELOPMENT]
# version: "3"

services:

  api:
    container_name: autoxkcd-api-d
    build:
      context: ..
      dockerfile: containers/auto-xkcd/Dockerfile
      target: dev
    env_file:
      - env_files/dev.env
    working_dir: /app
    command: ["python", "src/auto_xkcd/start_api.py"]

    #   ## Debugging entrypoints. Only uncomment 1 'entrypoint:' at a time
    #   # entrypoint: ["pwd"]
    #   # entrypoint: ["ls", "-la", "."]
    #   # entrypoint: ["ls", "-la", "/app"]

    volumes:
      - ../src:/app/src
      - ${AUTOXKCD_DATA_DIR:-./container_data/dev/auto-xkcd/data}:/app/.data
      - ${AUTOXKCD_LOGS_DIR:-./container_data/dev/auto-xkcd/logs}:/app/logs
    ports:
      - ${UVICORN_HOST_PORT:-8080}:8000
    environment:
      ENV_FOR_DYNACONF: dev
      DYNACONF_ENV: dev
      DYNACONF_CONTAINER_ENV: true
      DYNACONF_LOG_LEVEL: "DEBUG"
      DYNACONF_LOGS_DIR: "logs/dev"

      DYNACONF_DB_TYPE: ${DB_TYPE:-sqlite}
      DYNACONF_DB_DRIVERNAME: ${DB_DRIVERNAME:-sqlite+pysqlite}
      DYNACONF_DB_USERNAME: ${DB_USERNAME}
      DYNACONF_DB_PASSWORD: ${DB_PASSWORD}
      DYNACONF_DB_HOST: ${DB_HOST}
      DYNACONF_DB_PORT: ${DB_PORT}
      DYNACONF_DB_DATABASE: ${DB_DATABASE:-/app/.data/auto-xkcd.dev.sqlite}
      DYNACONF_DB_ECHO: ${DB_ECHO:-true}

      DYNACONF_MINIO_ADDRESS: ${AUTOXKCD_MINIO_ADDRESS:-""}
      DYNACONF_MINIO_PORT: ${AUTOXKCD_MINIO_PORT:-9000}
      DYNACONF_MINIO_HTTPS: ${AUTOXKCD_MINIO_HTTPS:-true}
      DYNACONF_MINIO_USERNAME: ${AUTOXKCD_MINIO_USERNAME:-auto-xkcd}
      DYNACONF_MINIO_PASSWORD: ${AUTOXKCD_MINIO_PASSWORD:-""}
      DYNACONF_MINIO_ACCESS_KEY: ${AUTOXKCD_MINIO_ACCESS_KEY:-""}
      DYNACONF_MINIO_ACCESS_SECRET: ${AUTOXKCD_MINIO_ACCESS_SECRET:-""}

      ##
      # FastAPI
      ##
      DYNACONF_FASTAPI_DEBUG: ${FASTAPI_DEBUG:-true}
      DYNACONF_FASTAPI_TITLE: ${FASTAPI_TITLE:-"[DEV] auto-xkcd"}
      DYNACONF_FASTAPI_SUMMARY: ${FASTAPI_SUMMARY:-"An overengineered app to get XKCD comics"}
      DYNACONF_FASTAPI_DESCRIPTION: ${FASTAPI_DESCRIPTION:-"API for getting XKCD comics. This is a learning project, and intentionally over-engineered as a result."}
      DYNACONF_FASTAPI_VERSION: ${FASTAPI_VERSION:-"0.1.0"}
      DYNACONF_FASTAPI_OPENAPI_URL: ${FASTAPI_OPENAPI_URL:-"/openapi.json"}
      DYNACONF_FASTAPI_REDIRECT_SLASHES: ${FASTAPI_REDIRECT_SLASHES:-true}
      DYNACONF_FASTAPI_DOCS_URL: ${FASTAPI_DOCS_URL:-"/docs"}
      DYNACONF_FASTAPI_REDOC_URL: ${FASTAPI_REDOC_URL:-"/redoc"}
      DYNACONF_FASTAPI_OPENAPI_PREFIX: ${FASTAPI_OPENAPI_PREFIX:-""}
      DYNACONF_FASTAPI_ROOT_PATH: ${FASTAPI_ROOT_PATH:-""}
      DYNACONF_FASTAPI_ROOT_PATH_IN_SERVERS: ${FASTAPI_ROOT_PATH_IN_SERVERS:-true}

      ##
      # Uvicorn
      ##
      DYNACONF_UVICORN_APP: ${UVICORN_APP:-api._main:app}
      DYNACONF_UVICORN_HOST: ${UVICORN_HOST:-"0.0.0.0"}
      DYNACONF_UVICORN_PORT: ${UVICORN_PORT:-8000}
      DYNACONF_UVICORN_ROOT_PATH: ${UVICORN_ROOT_PATH:-""}
      DYNACONF_UVICORN_RELOAD: ${UVICORN_RELOAD:-true}
      DYNACONF_UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL:-DEBUG}

      ##
      # TELEGRAM
      ##
      DYNACONF_TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME:-""}
      DYNACONF_TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-""}

  # autoxkcd:
  #   container_name: autoxkcd-d
  #   build:
  #     context: ..
  #     dockerfile: containers/auto-xkcd/Dockerfile
  #     target: dev
  #   env_file:
  #     - env_files/dev.env
  #   working_dir: /app
  #   command: ["python", "src/auto_xkcd/demo.py"]

  #   ## Debugging entrypoints. Only uncomment 1 'entrypoint:' at a time
  #   # entrypoint: ["pwd"]
  #   # entrypoint: ["ls", "-la", "."]
  #   # entrypoint: ["ls", "-la", "/app"]
  #   volumes:
  #     - ../src:/app/src
  #     - ${AUTOXKCD_DATA_DIR:-./container_data/dev/auto-xkcd/data}:/app/.data
  #     - ${AUTOXKCD_LOGS_DIR:-./container_data/dev/auto-xkcd/logs}:/app/logs
  #   environment:
  #     ENV_FOR_DYNACONF: dev
  #     DYNACONF_ENV: dev
  #     DYNACONF_CONTAINER_ENV: true
  #     DYNACONF_LOG_LEVEL: "DEBUG"
  #     DYNACONF_LOGS_DIR: "logs/dev"

  #     DYNACONF_MINIO_ADDRESS: ${AUTOXKCD_MINIO_ADDRESS:-""}
  #     DYNACONF_MINIO_PORT: ${AUTOXKCD_MINIO_PORT:-9000}
  #     DYNACONF_MINIO_HTTPS: ${AUTOXKCD_MINIO_HTTPS:-true}
  #     DYNACONF_MINIO_USERNAME: ${AUTOXKCD_MINIO_USERNAME:-auto-xkcd}
  #     DYNACONF_MINIO_PASSWORD: ${AUTOXKCD_MINIO_PASSWORD:-""}
  #     DYNACONF_MINIO_ACCESS_KEY: ${AUTOXKCD_MINIO_ACCESS_KEY:-""}
  #     DYNACONF_MINIO_ACCESS_SECRET: ${AUTOXKCD_MINIO_ACCESS_SECRET:-""}

  # autoxkcd-scraper:
  #   container_name: autoxkcd-scraper-d
  #   ## Enable rich printing
  #   tty: true
  #   build:
  #     context: ..
  #     dockerfile: containers/auto-xkcd/Dockerfile
  #     target: dev
  #   env_file:
  #     - env_files/dev.env
  #   working_dir: /app
  #   command: ["python", "-u", "src/auto_xkcd/cli.py", "pipelines", "scrape", "--overwrite-serial", "--loop-requests", "--max-loops", "0"]

    ## Debugging entrypoints. Only uncomment 1 'entrypoint:' at a time
    # entrypoint: ["pwd"]
    # entrypoint: ["ls", "-la", "."]
    # entrypoint: ["ls", "-la", "/app"]
    # volumes:
    #   - ../src:/app/src
    #   - ${AUTOXKCD_DATA_DIR:-./container_data/dev/auto-xkcd/data}:/app/.data
    #   - ${AUTOXKCD_LOGS_DIR:-./container_data/dev/auto-xkcd/logs}:/app/logs
    # environment:
    #   TERM: xterm-256color
    #   PYTHONUNBUFFERED: 1

    #   ENV_FOR_DYNACONF: dev
    #   DYNACONF_ENV: dev
    #   DYNACONF_CONTAINER_ENV: true
    #   DYNACONF_LOG_LEVEL: "DEBUG"
    #   DYNACONF_LOGS_DIR: "logs/dev"

    #   DYNACONF_DB_TYPE: ${DB_TYPE:-sqlite}
    #   DYNACONF_DB_DRIVERNAME: ${DB_DRIVERNAME:-sqlite+pysqlite}
    #   DYNACONF_DB_USERNAME: ${DB_USERNAME}
    #   DYNACONF_DB_PASSWORD: ${DB_PASSWORD}
    #   DYNACONF_DB_HOST: ${DB_HOST}
    #   DYNACONF_DB_PORT: ${DB_PORT}
    #   DYNACONF_DB_DATABASE: ${DB_DATABASE:-/app/.data/auto-xkcd.dev.sqlite}
    #   DYNACONF_DB_ECHO: ${DB_ECHO:-true}

    #   DYNACONF_MINIO_ADDRESS: ${AUTOXKCD_MINIO_ADDRESS:-""}
    #   DYNACONF_MINIO_PORT: ${AUTOXKCD_MINIO_PORT:-9000}
    #   DYNACONF_MINIO_HTTPS: ${AUTOXKCD_MINIO_HTTPS:-true}
    #   DYNACONF_MINIO_USERNAME: ${AUTOXKCD_MINIO_USERNAME:-auto-xkcd}
    #   DYNACONF_MINIO_PASSWORD: ${AUTOXKCD_MINIO_PASSWORD:-""}
    #   DYNACONF_MINIO_ACCESS_KEY: ${AUTOXKCD_MINIO_ACCESS_KEY:-""}
    #   DYNACONF_MINIO_ACCESS_SECRET: ${AUTOXKCD_MINIO_ACCESS_SECRET:-""}

  # autoxkcd-dbupdate:
  #   container_name: autoxkcd-dbupdate-d
  #   ## Enable rich printing
  #   tty: true
  #   build:
  #     context: ..
  #     dockerfile: containers/auto-xkcd/Dockerfile
  #     target: dev
  #   env_file:
  #     - env_files/dev.env
  #   working_dir: /app
  #   command: ["python", "-u", "src/auto_xkcd/cli.py", "pipelines", "update-db", "--overwrite-serial", "--continuous", "--loop-timeout", "3600"]

  #   ## Debugging entrypoints. Only uncomment 1 'entrypoint:' at a time
  #   # entrypoint: ["pwd"]
  #   # entrypoint: ["ls", "-la", "."]
  #   # entrypoint: ["ls", "-la", "/app"]
  #   volumes:
  #     - ../src:/app/src
  #     - ${AUTOXKCD_DATA_DIR:-./container_data/dev/auto-xkcd/data}:/app/.data
  #     - ${AUTOXKCD_LOGS_DIR:-./container_data/dev/auto-xkcd/logs}:/app/logs
  #   environment:
  #     TERM: xterm-256color
  #     PYTHONUNBUFFERED: 1

  #     ENV_FOR_DYNACONF: dev
  #     DYNACONF_ENV: dev
  #     DYNACONF_CONTAINER_ENV: true
  #     DYNACONF_LOG_LEVEL: "DEBUG"
  #     DYNACONF_LOGS_DIR: "logs/dev"

  #     DYNACONF_DB_TYPE: ${DB_TYPE:-sqlite}
  #     DYNACONF_DB_DRIVERNAME: ${DB_DRIVERNAME:-sqlite+pysqlite}
  #     DYNACONF_DB_USERNAME: ${DB_USERNAME}
  #     DYNACONF_DB_PASSWORD: ${DB_PASSWORD}
  #     DYNACONF_DB_HOST: ${DB_HOST}
  #     DYNACONF_DB_PORT: ${DB_PORT}
  #     DYNACONF_DB_DATABASE: ${DB_DATABASE:-/app/.data/auto-xkcd.dev.sqlite}
  #     DYNACONF_DB_ECHO: ${DB_ECHO:-true}

  #     DYNACONF_MINIO_ADDRESS: ${AUTOXKCD_MINIO_ADDRESS:-""}
  #     DYNACONF_MINIO_PORT: ${AUTOXKCD_MINIO_PORT:-9000}
  #     DYNACONF_MINIO_HTTPS: ${AUTOXKCD_MINIO_HTTPS:-true}
  #     DYNACONF_MINIO_USERNAME: ${AUTOXKCD_MINIO_USERNAME:-auto-xkcd}
  #     DYNACONF_MINIO_PASSWORD: ${AUTOXKCD_MINIO_PASSWORD:-""}
  #     DYNACONF_MINIO_ACCESS_KEY: ${AUTOXKCD_MINIO_ACCESS_KEY:-""}
  #     DYNACONF_MINIO_ACCESS_SECRET: ${AUTOXKCD_MINIO_ACCESS_SECRET:-""}

  # autoxkcd-currentcomic:
  #   container_name: autoxkcd-currentcomic-d
  #   ## Enable rich printing
  #   tty: true
  #   build:
  #     context: ..
  #     dockerfile: containers/auto-xkcd/Dockerfile
  #     target: dev
  #   env_file:
  #     - env_files/dev.env
  #   working_dir: /app
  #   command: ["python", "-u", "src/auto_xkcd/cli.py", "pipelines", "get-current", "--overwrite-serial", "--continuous", "--loop-timeout", "3600"]

  #   ## Debugging entrypoints. Only uncomment 1 'entrypoint:' at a time
  #   # entrypoint: ["pwd"]
  #   # entrypoint: ["ls", "-la", "."]
  #   # entrypoint: ["ls", "-la", "/app"]
  #   volumes:
  #     - ../src:/app/src
  #     - ${AUTOXKCD_DATA_DIR:-./container_data/dev/auto-xkcd/data}:/app/.data
  #     - ${AUTOXKCD_LOGS_DIR:-./container_data/dev/auto-xkcd/logs}:/app/logs
  #   environment:
  #     TERM: xterm-256color
  #     PYTHONUNBUFFERED: 1

  #     ENV_FOR_DYNACONF: dev
  #     DYNACONF_ENV: dev
  #     DYNACONF_CONTAINER_ENV: true
  #     DYNACONF_LOG_LEVEL: "DEBUG"
  #     DYNACONF_LOGS_DIR: "logs/dev"

  #     DYNACONF_DB_TYPE: ${DB_TYPE:-sqlite}
  #     DYNACONF_DB_DRIVERNAME: ${DB_DRIVERNAME:-sqlite+pysqlite}
  #     DYNACONF_DB_USERNAME: ${DB_USERNAME}
  #     DYNACONF_DB_PASSWORD: ${DB_PASSWORD}
  #     DYNACONF_DB_HOST: ${DB_HOST}
  #     DYNACONF_DB_PORT: ${DB_PORT}
  #     DYNACONF_DB_DATABASE: ${DB_DATABASE:-/app/.data/auto-xkcd.dev.sqlite}
  #     DYNACONF_DB_ECHO: ${DB_ECHO:-true}

  #     DYNACONF_MINIO_ADDRESS: ${AUTOXKCD_MINIO_ADDRESS:-""}
  #     DYNACONF_MINIO_PORT: ${AUTOXKCD_MINIO_PORT:-9000}
  #     DYNACONF_MINIO_HTTPS: ${AUTOXKCD_MINIO_HTTPS:-true}
  #     DYNACONF_MINIO_USERNAME: ${AUTOXKCD_MINIO_USERNAME:-auto-xkcd}
  #     DYNACONF_MINIO_PASSWORD: ${AUTOXKCD_MINIO_PASSWORD:-""}
  #     DYNACONF_MINIO_ACCESS_KEY: ${AUTOXKCD_MINIO_ACCESS_KEY:-""}
  #     DYNACONF_MINIO_ACCESS_SECRET: ${AUTOXKCD_MINIO_ACCESS_SECRET:-""}
