[default]

minio_password = ""
minio_access_key = ""
minio_access_secret = ""

[dev]

minio_password = ""
minio_access_key = ""
minio_access_secret = ""

[prod]

minio_password = ""
minio_access_key = ""
minio_access_secret = ""
