"""autogenerated migration

Revision ID: 2838aca92f65
Revises: 
Create Date: 2025-04-26 22:24:29.863544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2838aca92f65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comic_img', ['id'])
    op.create_unique_constraint(None, 'current_comic_meta', ['id'])
    op.create_unique_constraint(None, 'xkcd_comic', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xkcd_comic', type_='unique')
    op.drop_constraint(None, 'current_comic_meta', type_='unique')
    op.drop_constraint(None, 'comic_img', type_='unique')
    # ### end Alembic commands ###
