[database]
db_password = ""

[minio]
minio_secret_key = ""

[ntfy]
ntfy_password = "<your ntfy user password>"
ntfy_token = "<tk_...>"

[celery]
celery_broker_password = ""
celery_backend_password = ""
