[default]

env = "prod"
container_env = false
log_level = "INFO"
logs_dir = "logs"

[dev]

env = "dev"
container_env = false
log_level = "DEBUG"
logs_dir = "logs/dev"

[prod]

env = "prod"
container_env = false
log_level = "INFO"
logs_dir = "logs"
