[default]

minio_address = ""
minio_port = 9001
minio_username = "auto-xkcd"
## Set in .secrets.toml
# minio_password = ""
##  Set in .secrets.toml
# minio_access_key = ""
# minio_access_secret = ""

[dev]

minio_address = ""
minio_port = 9001
minio_username = "auto-xkcd"
## Set in .secrets.toml
# minio_password = ""
##  Set in .secrets.toml
# minio_access_key = ""
# minio_access_secret = ""

[prod]

minio_address = ""
minio_port = 9001
minio_username = "auto-xkcd"
## Set in .secrets.toml
# minio_password = ""
##  Set in .secrets.toml
# minio_access_key = ""
# minio_access_secret = ""
