[default]

UVICORN_APP = "api._main:app"
UVICORN_HOST = "0.0.0.0"
UVICORN_PORT = 8000
UVICORN_ROOT_PATH = "/"
UVICORN_RELOAD = false
UVICORN_LOG_LEVEL = "INFO"

[dev]

UVICORN_APP = "api._main:app"
UVICORN_HOST = "0.0.0.0"
UVICORN_PORT = 8080
UVICORN_ROOT_PATH = "/"
UVICORN_RELOAD = true
UVICORN_LOG_LEVEL = "DEBUG"

[prod]
