[default]

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
# Set in .secrets.toml
# db_password = ""
db_host = ""
db_port = ""
db_database = ".data/auto-xkcd.sqlite"
db_echo = false

[dev]

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
# Set in .secrets.toml
# db_password = ""
db_host = ""
db_port = ""
db_database = ".data/auto-xkcd.dev.sqlite"
db_echo = false

[prod]

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
# Set in .secrets.toml
# db_password = ""
db_host = ""
db_port = ""
db_database = ".data/auto-xkcd.sqlite"
db_echo = false
